### ISSUE TITLE
Intermittently Failing Tests

### ISSUE THREAD

**Issue by jdantonio** [ruby-concurrency/concurrent-ruby#263]
A running list of tests that occasionally fail and need to be fixed:

- [x] [Concurrent::Exchanger exchange without timeout can be reused](https://travis-ci.org/ruby-concurrency/concurrent-ruby/jobs/53489448)
- [x] [Concurrent::ScheduledTask instance #execute does nothing unless the state is :unscheduled](https://travis-ci.org/ruby-concurrency/concurrent-ruby/jobs/53586321)
- [x] [dataflow passes the values of dependencies into the block](https://travis-ci.org/ruby-concurrency/concurrent-ruby/jobs/53587463)
- ~~Exchanger tests deadlock and [never finish](https://travis-ci.org/ruby-concurrency/concurrent-ruby/jobs/55047572)~~ *Known bug. Will be rewritten from scratch after the 1.0 release.*
- ~~[Concurrent::ReadWriteLock#to_s includes the waiting writer count](https://travis-ci.org/ruby-concurrency/concurrent-ruby/jobs/55047574) *(NOTE: ReadWriteLock has not been released and a custom `to_s` method is not critical. Deleting the method is a viable option.)*~~
- [x] #timeout kills the thread on timeout
- [x] #timeout kills the thread on success
- [x] Concurrent::MVar spurious wake ups #modify returns TIMEOUT on timeout on an empty MVar
- [x] [Concurrent::TimerTask dereferenceable it should behave like dereferenceable defaults :dup_on_deref to false](https://travis-ci.org/ruby-concurrency/concurrent-ruby/jobs/55237542)
- [x] [Concurrent::CyclicBarrier#wait without timeout should block the thread](https://travis-ci.org/ruby-concurrency/concurrent-ruby/jobs/55237542)
- [x] [Concurrent::TimerSet executes a given task when given a Time](https://travis-ci.org/ruby-concurrency/concurrent-ruby/jobs/55874348)
- [x] "Concurrent::Condition with many waiting threads signaled wake up broadcast wakes up all threads" not able to reproduce on os x rbx-2.5.2
- [x] [Concurrent::Edge futures .schedule scheduled execution in graph](https://travis-ci.org/ruby-concurrency/concurrent-ruby/jobs/60946747)
- [x] [Concurrent::TimerTask dereferenceable it should behave like dereferenceable defaults :dup_on_deref to false](https://travis-ci.org/ruby-concurrency/concurrent-ruby/jobs/61219215)
- [x] [Concurrent::Condition with many waiting threads signalled wake up #broadcast wakes up all threads](https://travis-ci.org/ruby-concurrency/concurrent-ruby/jobs/61229382)
- [x] [#atomically provides weak isolation](https://travis-ci.org/ruby-concurrency/concurrent-ruby/jobs/61229382)
- [x] Ruby cached thread pool [stress should be <= 200](https://travis-ci.org/ruby-concurrency/concurrent-ruby/jobs/61692385)
- [x] [Concurrent::ScheduledTask behavior it should behave like dereferenceable supports dereference flags with observers](https://travis-ci.org/ruby-concurrency/concurrent-ruby/jobs/63011979)

====

~~Output from tests that failed locally rather than on TravisCI:~~

```
Failures:

  1) #timeout kills the thread on timeout
     Failure/Error: expect(Thread).to receive(:kill).with(any_args())
       (<Thread (class)>).kill(*(any args))
           expected: 1 time with any arguments
           received: 1443 times with any arguments
     # ./spec/concurrent/utility/timeout_spec.rb:35:in `block (2 levels) in <module:Concurrent>'

  2) #timeout kills the thread on success
     Failure/Error: expect(Thread).to receive(:kill).with(any_args())
       (<Thread (class)>).kill(*(any args))
           expected: 1 time with any arguments
           received: 123 times with any arguments
     # ./spec/concurrent/utility/timeout_spec.rb:30:in `block (2 levels) in <module:Concurrent>'

  3) Concurrent::MVar spurious wake ups #modify returns TIMEOUT on timeout on an empty MVar
     Failure/Error: expect(result).to be_nil
       expected: nil
            got: #<Object:0x007ff9d9560740>
     # ./spec/concurrent/mvar_spec.rb:345:in `block (4 levels) in <module:Concurrent>'
```
